project:
  type: website
  execute-dir: project
 
website:
  navbar:
    logo: images/logo.jpg
    left:
      - href: index.qmd
        text: Home
      - href: part1/0_1_programming.qmd
        text: 1. 프로그래밍 기본기
      - href: part2/1_1_env.qmd
        text: 2. 환경 구축하기
      - href: part3/2_1_table1.qmd
        text: 3. R script 활용하기
      - href: part4/3_1_vibecoding.qmd
        text: 4. 결과 및 마무리
 
  sidebar:
    style: docked
    contents:
      - section: "1. 프로그래밍 기본기"
        contents: "part1/*.qmd"
      - section: "2. 환경 구축하기"
        contents: "part2/*.qmd"
      - section: "3. R script 활용하기"
        contents: "part3/*.qmd"
      - section: "4. 결과 및 마무리"
        contents: "part4/*.qmd"
 
  page-footer:
    left: "Copyright 2026, Eunji"
 
format:
  html: 
    theme: cosmo
    css: custom.css
    toc: true
    toc-location: right
    page-layout: full
 
execute:
  freeze: auto
  warning: false
  message: false
  
    # right:
    #   - text: "EN"
    #     href: en/index.qmd
    #   - text: "KO"
    #     href: ko/index.qmd

  # sidebar:
    #   contents: auto
    # style: docked
  #     background: dark
    # pdf:
    # mainfont: "KoPubWorldDotum"
    # mainfontoptions:
    #   - Path=C:/Windows/Fonts/
    #   - Extension=.ttf
    #   - UprightFont=KoPubWorld Dotum Medium
    #   - BoldFont=KoPubWorld Dotum Bold
    # pdf-engine: xelatex
    # include-in-header:
    #   text: |
    #     \usepackage{emoji}
    #     \setemojifont{Segoe UI Emoji}